name: Axio Media
favicon: null
layout_spectrum: 0.9193069541361183
typography_spectrum: 0.05919685959815979
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101010'
    - '#f1f1f1'
    - '#725c55'
    - '#bbaca7'
    - '#fc5556'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5932345266919583
  rhythmicContrast: 0
purpose: []
